### ISSUE TITLE
Failed to run flutter_app 0.7.0-0

### ISSUE THREAD

**Issue by RajatDBazaar** [bdero/flutter_scene#51] opened 2024-12-19 11:47 UTC
When we try to run the project, it fails and gives errors. 

```
dbtech@Developers-Mac-mini flutter_app % flutter run -d macos --enable-impeller
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008112-000138861199A01E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008112-000138861199A01E, name:My Mac }
Unhandled exception:
Exception: Failed to run flutter_scene_importer:import command in build hook (exit code 255):
STDERR: Building assets for package:flutter_scene_importer failed.
build_output.json contained a format error.

Contents: {"version":"1.5.0","timestamp":"2024-12-19 17:09:32.000","dependencies":[]}.
Only compatible versions with 1.6.0 are supported (was: 1.5.0).

Error: Compiling native assets failed.

STDOUT: 
#0      buildModels (package:flutter_scene_importer/build_hooks.dart:46:7)
#1      main.<anonymous closure> (file:///Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/hook/build.dart:6:5)
#2      build (package:native_assets_cli/src/api/build.dart:101:16)
#3      main (file:///Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/hook/build.dart:5:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
  Building assets for package:example_app failed.
  build.dart returned with exit code: 255.
  To reproduce run:
  /Users/dbtech/development/flutter/bin/dart --packages=/Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/.dart_tool/package_config.json /Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/.dart_tool/native_assets_builder/6597316917692e3e927f12d99369389a/hook.dill --config=/Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/.dart_tool/native_assets_builder/6597316917692e3e927f12d99369389a/config.json
  stderr:
  Unhandled exception:
Exception: Failed to run flutter_scene_importer:import command in build hook (exit code 255):
STDERR: Building assets for package:flutter_scene_importer failed.
build_output.json contained a format error.

Contents: {"version":"1.5.0","timestamp":"2024-12-19 17:09:32.000","dependencies":[]}.
Only compatible versions with 1.6.0 are supported (was: 1.5.0).

Error: Compiling native assets failed.

STDOUT: 
#0      buildModels (package:flutter_scene_importer/build_hooks.dart:46:7)
#1      main.<anonymous closure> (file:///Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/hook/build.dart:6:5)
#2      build (package:native_assets_cli/src/api/build.dart:101:16)
#3      main (file:///Users/dbtech/development/flutterProject/flutter_scene/examples/flutter_app/hook/build.dart:5:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)

  stdout:


Target dart_build failed: Error: Building native assets failed. See the logs for more details.

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

Building macOS application...                                           
Error: Build process failed
```

**Comment by domesticmouse** [comment] 2024-12-19 19:31
See also https://github.com/bdero/flutter_scene/issues/48

**Comment by bdero** [comment] 2024-12-19 21:00
Closing as duplicate of https://github.com/bdero/flutter_scene/issues/48

**Closed by bdero** 2024-12-19 21:00 UTC
Labels: duplicate
